coredac/dataflow

include/NeuraDialect/NeuraOps.td
include/Transforms/InsertMovPass.h
lib/CMakeLists.txt
lib/Conversion/ArithToNeura/ArithToNeura.cpp
lib/Transforms/CMakeLists.txt
lib/Transforms/InsertMovPass.cpp
test/neura/add.mlir
tools/mlir-neura-opt/CMakeLists.txt
tools/mlir-neura-opt/mlir-neura-opt.cpp

A neura.mov to connect operations.

Declare and define mov

---

include/NeuraDialect/NeuraOps.td
lib/Conversion/LlvmToNeura/LlvmToNeuraPass.cpp
lib/Conversion/LlvmToNeura/LlvmToNeuraPatterns.td
lib/Transforms/CMakeLists.txt
lib/Transforms/FusePatternsPass.cpp
lib/Transforms/InsertMovPass.cpp
test/neura/fadd_fadd.mlir
test/neura/for_loop/kernel.cpp
test/neura/for_loop/test.mlir
tools/mlir-neura-opt/CMakeLists.txt
tools/mlir-neura-opt/mlir-neura-opt.cpp

- Enable lower passes to work on `ModuleOp`
- To make it be able to parse both llvm.func and mlir.func
- First step towards https://github.com/coredac/dataflow/issues/10
- Introduce some other basic neura operations (vector floating add, i.e., vfadd) and fusion patterns (mul->add)

Enable pass running on module

---

.github/workflows/main.yml
include/Common/AcceleratorAttrs.h
include/NeuraDialect/NeuraOps.td
include/Transforms/AssignAcceleratorPass.h
lib/Conversion/LlvmToNeura/LlvmToNeuraPass.cpp
lib/Conversion/LlvmToNeura/LlvmToNeuraPatterns.td
lib/Transforms/AssignAcceleratorPass.cpp
lib/Transforms/CMakeLists.txt
test/neura/arith_add.mlir
test/neura/for_loop/test.mlir
test/neura/interpreter/interpreter.mlir
test/neura/llvm_add.mlir
tools/mlir-neura-opt/mlir-neura-opt.cpp

- Kernels except main are tagged
- All ops within a typical for loop are supported/lowered
TODO:

Tag kernel with accelerator attr for optional lowering

---

include/NeuraDialect/NeuraOps.td
lib/Conversion/LlvmToNeura/LlvmToNeuraPatterns.td
test/neura/interpreter/interpreter.mlir
test/neura/interpreter/lower_and_interpret_subf.mlir
test/neura/llvm_sub.mlir
tools/neura-interpreter/neura-interpreter.cpp

regarding #13 , I will add more Ops if this looks fine.
Please let me know if this is not what we are looking for.
Thanks!

support llvm_fsub

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/LeveragePredicatedValuePass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp

Prototype ctrl to data flow transformation
- Insert Phi at the beginning of each basic block
- Connecting the predecessors with the newly inserted phi
- Remove basic block
TODO:

Prototype ctrl to data transformation

---

lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/neura/ctrl/branch.mlir

When a block has only a single predecessor block, we don't actually need a phi node. This PR avoids inserting phi node with single operand.

Avoid unnecessary phi

---

lib/Conversion/ArithToNeura/ArithToNeuraPass.cpp

add arith to neura for fmul 

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/neura/ctrl/branch_for.mlir

Enable loop ctrl with placeholder for SSA and backward ctrl move, basically,
- `neura.reserve` is added as a phi's operand if the real dependent value is defined within the same block but after the phi's creation
- Insert the backward ctrl move after the real value's define, to indicate there is a loop-carried dependency without violating SSA
The provided test can demonstrate this PR's funtionality:
```
func.func @loop_test() -> f32 {
%n = llvm.mlir.constant(10 : i64) : i64
%c0 = llvm.mlir.constant(0 : i64) : i64
%c1 = llvm.mlir.constant(1 : i64) : i64
%c1f = llvm.mlir.constant(3.0 : f32) : f32
%acc_init = llvm.mlir.constant(0.0 : f32) : f32
llvm.br ^bb1(%c0, %acc_init : i64, f32)
^bb1(%i: i64, %acc: f32):  // loop body + check + increment
%next_acc = llvm.fadd %acc, %c1f : f32
%i_next = …
```

Enable loop ctrl with placeholder for SSA and backward ctrl move

---

include/NeuraDialect/NeuraOps.td
include/NeuraDialect/NeuraPasses.h
include/NeuraDialect/NeuraPasses.td
lib/NeuraDialect/Transforms/CMakeLists.txt
lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/neura/ctrl/branch.mlir
test/neura/ctrl/branch_for.mlir
test/neura/ctrl/branch_no_arg.mlir
test/neura/ctrl/nested_branch.mlir

Previous ctrl->data flow is not correct, this PR introduces `grant_predicate` and `grant_once` to make sure the `cond_br` can pass proper condition towards the successor blocks.
We also prototype the simple mapping pass by introducing the `RecMII` calculator.
This PR also touches return: https://github.com/coredac/dataflow/issues/33, maybe we can identify the termination by checking the `return`'s predicate is 1 or 0.

Provide grant_predicate and calculate RecMII

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/neura/ctrl/branch_for.mlir
test/neura/ctrl/branch_with_and_without_arg.mlir
test/neura/ctrl/branch_without_arg.mlir

Introduce `grant_always` operation.
- The `grant_always` is different from `grant_once`, but both are within entry block.
- New test is added.
- Create a case that a variable (in entry block) is used by both branch's argument and non-arg style that is directly consumed by successor blocks.

Introduce grant_always operation

---

include/NeuraDialect/mapping/mapping_util.h
lib/NeuraDialect/Transforms/CMakeLists.txt
lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
lib/NeuraDialect/Transforms/mapping/mapping_util.cpp
test/neura/ctrl/branch_for.mlir

- Provide resMII calculation
- Re-org util funcs
- Extreme simple arch spec structure is provided
TODO:

Re-organize mapping util functions

---

include/Conversion/ConversionPasses.h
include/Conversion/ConversionPasses.td
include/NeuraDialect/NeuraOps.td
include/NeuraDialect/NeuraPasses.td
lib/Conversion/ArithToNeura/ArithToNeuraPass.cpp
lib/Conversion/BuiltinToNeura/BuiltinToNeuraPass.cpp
lib/Conversion/BuiltinToNeura/CMakeLists.txt
lib/Conversion/CMakeLists.txt
lib/Conversion/LlvmToNeura/LlvmToNeuraPass.cpp
lib/Conversion/LlvmToNeura/LlvmToNeuraPatterns.td
lib/Conversion/MemRefToNeura/MemRefToNeuraPass.cpp
lib/NeuraDialect/NeuraPasses.cpp
test/affine2neura/bert/bert_node0/bert_node0.mlir
test/affine2neura/bert/bert_node1/bert_node1.mlir
test/affine2neura/bert/bert_node2/bert_node2.mlir
test/affine2neura/bert/bert_node28/bert_node28.mlir
test/affine2neura/bert/bert_node3/bert_node3.mlir
test/affine2neura/bert/bert_node8/bert_node8.mlir
test/affine2neura/bert/bert_node9/bert_node9.mlir
test/arith2neura/add.mlir
test/neura/arith_add.mlir
test/neura/ctrl/branch_without_arg.mlir
test/neura/fadd_fadd.mlir
test/samples/bert/bert_affine.mlir

In this pr:
- Add lowering from `memref` and `builtin` dialects
- Add `neura.load_indexed/store_indexed` operation for `memref` like memory access
- Fix some typos in files
Now, we can write code in `cpp` and lower it to `affine` dialect using `polygeist`. And more high-level transforms can be implemented in `affine` level, like polyhedral-based optimization, loop-unroll/fusion/fission/interchange/tiling/vectorize, etc.

Enable end2end affine-to-neura lowering

---

include/NeuraDialect/CMakeLists.txt
include/NeuraDialect/NeuraOps.td
lib/Conversion/CMakeLists.txt
lib/NeuraDialect/CMakeLists.txt
lib/NeuraDialect/Transforms/LeveragePredicatedValuePass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/affine2neura/bert/bert_node0/bert_node0.mlir
test/affine2neura/bert/bert_node1/bert_node1.mlir
test/affine2neura/bert/bert_node28/bert_node28.mlir
test/neura/ctrl/branch.mlir
test/neura/ctrl/branch_for.mlir
test/neura/ctrl/branch_with_and_without_arg.mlir
test/neura/ctrl/branch_without_arg.mlir

In this PR, an edge-based control flow to data flow transform pass is implemented.
Basically, we can categorize all the edges in CFG into the following 8 cases:
1. Backward cond_br edges with values.
2. Backward br edges with values.
3. Backward cond_br without values.
4. Backward br without value.
5. Forward cond_br edges with values.
6. Forward br edges with values.
7. Forward cond_br edges without values.
8. Forward br edges without values.
Cases 3 and 4 do not appear in the current benchmarks. Since they correspond to control flow jumps for statements like `goto`, we do not consider these cases for now.
The transform is implemented based on the remaining six edges.
For the target block of the edge in case 7, we chose to `grant_predicate` all results in this block based on condition to …

Refactor the Ctrl to Data Flow Implementation Logic

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/GenerateCodePass.cpp
lib/NeuraDialect/Transforms/LeveragePredicatedValuePass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/neura/for_loop/test.mlir

Enable ctrl to data flow lowering for llvm.func

[feature] Enable ctrl to data flow lowering for llvm.func

---

include/NeuraDialect/NeuraPasses.h
include/NeuraDialect/NeuraPasses.td
lib/NeuraDialect/Transforms/CMakeLists.txt
lib/NeuraDialect/Transforms/CanonicalizeCastPass.cpp
test/controflow_fuse/perfect_nested/perfect_nested.mlir
test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
test/controflow_fuse/simpleloop/simpleloop.mlir

In this pr:
- Add a pass to convert all `index` types to `i64`
- Remove non-sense `index_to_i64` or `i64_to_index` cast operations

Remove non-sense neura::cast ops

---

include/NeuraDialect/Architecture/Architecture.h
lib/NeuraDialect/Architecture/Architecture.cpp
lib/NeuraDialect/Mapping/mapping_util.cpp

Prepare the Function Unit and Registers for mapping. A tile could contain registers and functional units
- hierarchi: `Tile` -> `Register File Cluster` -> `Register File` -> `Register`, https://github.com/coredac/dataflow/issues/81
- @Jackcuii I have prototyped the Function Unit for you, please honor the arch spec to initialize them, `TODO with @Jackcuii` are left as comments, https://github.com/coredac/dataflow/issues/82 https://github.com/coredac/dataflow/issues/52
TODO:
- Relax the mapping constraint on the input channel by moving data from the channel to local registers
- Register might also be modeled in MRRG, https://github.com/coredac/dataflow/issues/81

Prepare Function Unit and Registers for mapping

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/FuseControlFlowPass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/affine2neura/bert/bert_node1/bert_node1.mlir
test/affine2neura/bert/bert_node28/bert_node28.mlir
test/controflow_fuse/complex_nested/complex_nested.mlir
test/controflow_fuse/non_perfect_nested/non_perfect_nested.mlir
test/controflow_fuse/perfect_nested/perfect_nested.mlir
test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
test/controflow_fuse/simpleloop/simpleloop.mlir
test/neura/ctrl/branch_for.mlir
test/neura/ctrl/nested_branch.mlir
test/neura/for_loop/test.mlir

In this pr:
- Remove the `grant_always` operations in `--transform-ctrl-to-data-pass`
- After removing the `grant_always`, we can achive `CompiledII = 6 : i32, RecMII = 4 : i32, ResMII = 2 : i32` for `branch_for.mlir` (previous compiledII=7) and `CompiledII = 3 : i32, RecMII = 3 : i32, ResMII = 2 : i32` for `simpleloop.mlir` (previous compiledII=5).

Remove grant_always

---

lib/NeuraDialect/Transforms/CanonicalizeLiveInPass.cpp
lib/NeuraDialect/Transforms/FuseControlFlowPass.cpp
lib/NeuraDialect/Transforms/MapToAcceleratorPass.cpp
lib/NeuraDialect/Transforms/TransformCtrlToDataFlowPass.cpp
test/affine2neura/bert/bert_node1/bert_node1.mlir
test/affine2neura/bert/bert_node28/bert_node28.mlir
test/controflow_fuse/complex_nested/complex_nested.mlir
test/controflow_fuse/non_perfect_nested/non_perfect_nested.mlir
test/controflow_fuse/perfect_nested/perfect_nested.mlir
test/controflow_fuse/perfect_reduction/perfect_reduction.mlir
test/controflow_fuse/simple_loop/simple_loop.mlir
test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.mlir
test/mapping_quality/branch_for.mlir
test/mapping_quality/tiny_loop.mlir
test/neura/ctrl/branch_for.mlir
test/neura/ctrl/for_with_if.mlir
test/neura/ctrl/nested_branch.mlir
test/neura/for_loop/test.mlir

In previous `--canonicalize-live-in` pass, we traverse the blocks in topological order. But for case like:
```
module {
func.func @_Z10bert_node1PA1_A1_A1_A1_A128_bPA1_A128_S1_(%arg0: memref<?x1x1x1x1x128xi8>, %arg1: memref<?x1x128x1x1x128xi8>) attributes {accelerator = "neura", llvm.linkage = #llvm.linkage<external>} {
%0 = "neura.constant"() <{value = 1 : index}> : () -> index
%1 = "neura.constant"() <{value = 128 : index}> : () -> index
%2 = "neura.constant"() <{value = 0 : index}> : () -> index
%3 = "neura.cast"(%2) <{cast_type = "index_to_int"}> : (index) -> i64
neura.br %3 : i64 to ^bb1
^bb1(%4: i64):  // 2 preds: ^bb0, ^bb5
%5 = "neura.cast"(%4) <{cast_type = "int_to_index"}> : (i64) -> index
%6 = "neura.icmp"(%5, %1) <{cmpType = "slt"}> : (index, index) -> i1
neura.cond_br %6 : i1 …
```

Fix the bug in canonicalize-live-in pass

---

lib/NeuraDialect/Transforms/GenerateCodePass.cpp
test/code_gen/README.md
test/code_gen/test_code_generate.mlir
test/mapping_quality/branch_for.mlir
test/neura/ctrl/branch_for.mlir

The format has been revised. Whereas our YAML previously mapped one entry to one operation, it now adheres to the Entry → Instructions → Operations structure. Each core has only one entry for now (will be more entries in the future); each entry contains an ordered list of instructions. Every instruction is stamped by a timestep and contains one or more operations that execute in that timestep. Each operation specifies an opcode, src_operands, and dst_operands. For example:

Modify the yaml format

---

include/NeuraDialect/NeuraOps.td
lib/NeuraDialect/Transforms/Optimizations/HwSpecificOpt/FuseLoopControlPass.cpp
test/controflow_fuse/simple_loop/simple_loop.mlir
test/controflow_fuse/simple_loop_reduction/simple_loop_reduction.mlir
test/mapping_quality/tiny_loop.mlir

We provide a stream-based loop controller here for a single loop.
We embed all the constant loop info as attributes into the `loop_control` operation, e.g., step, start, end, etc.
This can greatly reduce the fan-ins for `loop_control` and get better mapping results.

Refactor Single Loop Fusing Logic
